export function renderCliHelp(): string {
  return [
    "aiyou-team CLI",
    "",
    "Usage:",
    "  aiyou-team setup [--with-opencode] [--yes] [--channel <stable|next>] [--install-root <path>] [--config-path <path>] [--dry-run] [--no-doctor]",
    "  aiyou-team update [--channel <stable|next>] [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  aiyou-team install [--source <local|registry>] [--local-tarball <path>] [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  aiyou-team install:local:user [--local-tarball <path>] [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  aiyou-team install:registry:user [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  aiyou-team uninstall [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  aiyou-team uninstall:user [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  aiyou-team doctor [--install-root <path>] [--config-path <path>] [--project-worktree <path>]",
    "  aiyou-team validate [--config-path <path>] [--project-worktree <path>] [--json]",
    "  aiyou-team version [--install-root <path>] [--json]",
    "  aiyou-team help",
    "",
    "Recommended:",
    "  npx aiyou-team@latest setup --with-opencode",
    "",
    "Install model:",
    "  setup      Check OpenCode, install aiyou-team into the OpenCode user-level workspace, write plugin entry, run doctor.",
    "  registry   Install aiyou-team from npm as the canonical package-name plugin entry: aiyou-team.",
    "  local      Development-only local tarball install.",
    "",
    "Compatibility aliases:",
    "  --tarball      Deprecated alias for --local-tarball",
    "  --config       Deprecated alias for --config-path",
  ].join("\n");
}
