export function renderCliHelp(): string {
  return [
    "CrewBee CLI",
    "",
    "Usage:",
    "  crewbee setup [--with-opencode] [--yes] [--channel <stable|next>] [--install-root <path>] [--config-path <path>] [--dry-run] [--no-doctor]",
    "  crewbee update [--channel <stable|next>] [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  crewbee install [--source <local|registry>] [--local-tarball <path>] [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  crewbee install:local:user [--local-tarball <path>] [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  crewbee install:registry:user [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  crewbee uninstall [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  crewbee uninstall:user [--install-root <path>] [--config-path <path>] [--dry-run]",
    "  crewbee doctor [--install-root <path>] [--config-path <path>] [--project-worktree <path>]",
    "  crewbee validate [--config-path <path>] [--project-worktree <path>] [--json]",
    "  crewbee version [--install-root <path>] [--json]",
    "  crewbee help",
    "",
    "Recommended:",
    "  npx crewbee@latest setup --with-opencode",
    "",
    "Install model:",
    "  setup      Check OpenCode, install CrewBee into the OpenCode user-level workspace, write plugin entry, run doctor.",
    "  registry   Install CrewBee from npm as the canonical package-name plugin entry: crewbee.",
    "  local      Development-only local tarball install.",
    "",
    "Compatibility aliases:",
    "  --tarball      Deprecated alias for --local-tarball",
    "  --config       Deprecated alias for --config-path",
  ].join("\n");
}
